# the title of your website
title: kkotyillustrations

# technical options
url: https://kkotyillustrations.com/
baseurl:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: pretty
sass:
  sourcemap: never