title: kkotyillustrations
tagline: Artistically talented, tastefully abnormal
description: The personal portfolio website for Karina Kotyleva
author: Karina Kotyleva

social:
  name: Karina Kotyleva
  links:
    - https://www.instagram.com/kkotyillustrations

# technical options
url: https://kkotyillustrations.com/
baseurl:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: pretty
sass:
  sourcemap: never